const tripData = {
  trip: {
    title: "意大利旅行计划",
    subtitle: "2026年6月10日-16日 · 6晚7天",
    route: ["罗马", "佛罗伦萨", "威尼斯 / Mestre"],
    traveler: "Solo 旅行者",
    outbound: "6月10日 08:10 EMA → 罗马 CIA（FR1542）",
    inbound: "6月16日 18:35 威尼斯 VCE → 曼彻斯特（FR2899）",
    version: "文档修订日期：2026年6月9日 · 版本：v3",
  },
  modules: [
    {
      title: "路线总览",
      description: "住宿、票据、日程与预算参考。",
      href: "./overview.html",
    },
    {
      title: "每日行程",
      description: "按天查看景点顺序、移动逻辑与地图。",
      href: "./itinerary.html",
    },
    {
      title: "餐饮指南",
      description: "三座城市的代表菜与用餐建议。",
      href: "./food.html",
    },
    {
      title: "Solo旅行安全提示",
      description: "高风险区域、财物策略与紧急信息。",
      href: "./safety.html",
    },
    {
      title: "预订清单",
      description: "已购、待购、可选项目一页核查。",
      href: "./booking.html",
    },
    {
      title: "JoJo的奇妙冒险打卡",
      description: "行程内外打卡点与总地图。",
      href: "./jojo.html",
    },
  ],
  stays: [
    {
      city: "罗马",
      address: "Via Ricasoli 19, Rome 00185",
      type: "民宿",
      dates: "6月10日 - 6月13日",
      googleQuery: "Via Ricasoli 19 Rome 00185",
    },
    {
      city: "佛罗伦萨",
      address: "Via Cosimo Rosselli 42 附近",
      type: "民宿",
      dates: "6月13日 - 6月15日",
      googleQuery: "Via Cosimo Rosselli 42 Florence",
    },
    {
      city: "威尼斯 Mestre",
      address: "Via Aleardo Aleardi 111, Veneto 30172",
      type: "民宿",
      dates: "6月15日 - 6月16日",
      googleQuery: "Via Aleardo Aleardi 111 Mestre Veneto 30172",
      note: "住在 Mestre 进岛约 10 分钟，去机场也更方便。",
    },
  ],
  tickets: [
    { date: "6月10日", label: "FR1542", route: "EMA 08:10 → ROM CIA 11:45", note: "已购" },
    { date: "6月13日", label: "高铁", route: "Roma Termini 10:35 → Firenze SMN 12:11", note: "已购" },
    { date: "6月15日", label: "高铁", route: "Firenze SMN 10:20 → Venezia Mestre 12:23", note: "已购" },
    { date: "6月16日", label: "FR2899", route: "VCE 18:35 → MAN 20:05", note: "已购" },
  ],
  schedule: [
    { date: "6月10日 周三", place: "罗马", theme: "抵达 + 历史中心轻松游" },
    { date: "6月11日 周四", place: "罗马", theme: "卡拉卡拉浴场 + 斗兽场（跟团）" },
    { date: "6月12日 周五", place: "罗马", theme: "梵蒂冈（跟团）+ 著名大教堂" },
    { date: "6月13日 周六", place: "罗马 → 佛罗伦萨", theme: "移动日（10:35出发）+ 傍晚全景" },
    { date: "6月14日 周日", place: "佛罗伦萨", theme: "大教堂 + 乌菲兹" },
    { date: "6月15日 周一", place: "佛罗伦萨 → 威尼斯 Mestre", theme: "移动日（10:20出发）+ 运河游览" },
    { date: "6月16日 周二", place: "威尼斯 → 回程", theme: "上午游览 + 18:35 回程" },
  ],
  days: [
    {
      id: "day-1",
      short: "Day 1",
      title: "6月10日 · 抵达罗马",
      city: "罗马",
      theme: "抵达 + 历史中心轻松游",
      alert: "今天不排重点景点，优先适应时差和节奏。",
      transport: [
        "08:10 EMA 出发，FR1542；约 11:45 落地罗马 CIA。",
        "乘 Terravision 大巴到 Roma Termini，约 45 分钟，€7。",
        "民宿在 Via Ricasoli 19，距 Termini 步行约 15 分钟或地铁一站。",
      ],
      plan: [
        "办理入住后步行探索周边。",
        "先看万神殿、纳沃纳广场，再往特拉斯特维列方向走。",
        "途经圣天使堡及圣天使桥，傍晚在 Trastevere 附近吃饭。",
      ],
      highlights: [
        "万神殿：外观 Free，内部 €5。",
        "纳沃纳广场：巴洛克喷泉群，Free。",
        "圣天使堡及圣天使桥：外观 Free，登顶可选 €16。",
        "特拉斯特维列区：中世纪小街，生活感很强。",
      ],
      food: ["cacio e pepe", "carbonara"],
      tips: [
        "第一天不建议把晚餐安排得太远。",
        "历史中心石板路较多，拖行李会比较颠。",
      ],
      mapCenter: [41.8987, 12.4734],
      mapZoom: 13,
      spots: [
        { order: 1, label: "万神殿", coords: [41.8986, 12.4769], note: "距住处步行约 15 分钟。", googleQuery: "Pantheon Rome" },
        { order: 2, label: "纳沃纳广场", coords: [41.8992, 12.4731], note: "JoJo 背景氛围点。", googleQuery: "Piazza Navona Rome" },
        { order: 3, label: "圣天使堡与圣天使桥", coords: [41.9031, 12.4663], note: "JoJo 打卡，河边景观好。", googleQuery: "Castel Sant'Angelo Rome" },
        { order: 4, label: "特拉斯特维列", coords: [41.8897, 12.4708], note: "晚上最适合收尾。", googleQuery: "Trastevere Rome" },
      ],
    },
    {
      id: "day-2",
      short: "Day 2",
      title: "6月11日 · 卡拉卡拉浴场 + 斗兽场（跟团）",
      city: "罗马",
      theme: "古罗马遗迹高密度日",
      alert: "今天步行量较大，斗兽场周边要特别注意扒手。",
      transport: [
        "地铁 B 线到 Circo Massimo，步行约 10 分钟到卡拉卡拉浴场。",
        "浴场到斗兽场步行约 25 分钟，可顺看马克西姆斯竞技场。",
        "13:45 斗兽场跟团已购，建议提前 20 分钟到集合点。",
      ],
      plan: [
        "上午 09:00 左右先看卡拉卡拉浴场。",
        "午餐在斗兽场附近找街边小馆。",
        "下午跟团，傍晚看卡比托利欧广场；骑士团锁孔可选。",
      ],
      highlights: [
        "卡拉卡拉浴场：€8。",
        "马克西姆斯竞技场：Free，外观即可。",
        "斗兽场：跟团已含罗马广场和帕拉蒂诺山。",
        "君士坦丁凯旋门：Free。",
        "卡比托利欧广场：眺望罗马广场废墟。",
      ],
      food: ["amatriciana", "saltimbocca alla romana"],
      tips: [
        "废墟区域遮阴少，帽子和水很重要。",
        "古迹区饮水泉很多，可以随手补水。",
      ],
      mapCenter: [41.886, 12.4905],
      mapZoom: 13,
      spots: [
        { order: 1, label: "卡拉卡拉浴场", coords: [41.879, 12.4923], note: "建议开门后直接入场。", googleQuery: "Terme di Caracalla Rome" },
        { order: 2, label: "马克西姆斯竞技场", coords: [41.886, 12.4853], note: "沿线顺看。", googleQuery: "Circus Maximus Rome" },
        { order: 3, label: "斗兽场", coords: [41.8902, 12.4922], note: "JoJo 核心打卡点。", googleQuery: "Colosseum Rome" },
        { order: 4, label: "君士坦丁凯旋门", coords: [41.8898, 12.4909], note: "就在斗兽场旁。", googleQuery: "Arch of Constantine Rome" },
        { order: 5, label: "卡比托利欧广场", coords: [41.8932, 12.4829], note: "傍晚视角很合适。", googleQuery: "Campidoglio Rome" },
        { order: 6, label: "骑士团锁孔", coords: [41.8826, 12.4831], note: "可选支线，游客较少。", googleQuery: "Knights of Malta Keyhole Rome" },
      ],
    },
    {
      id: "day-3",
      short: "Day 3",
      title: "6月12日 · 梵蒂冈（跟团）+ 著名大教堂",
      city: "罗马",
      theme: "宗教艺术主线",
      alert: "进入教堂需注意着装，短裤和露肩上衣可能被限制。",
      transport: [
        "09:00 梵蒂冈博物馆 + 西斯廷礼拜堂跟团已购。",
        "午间在圣彼得大教堂和广场活动。",
        "下午用地铁 A 线串联 San Giovanni、Santa Croce、Santa Maria Maggiore。",
      ],
      plan: [
        "上午跟团路线：松果庭院、地图画廊、拉斐尔画室、西斯廷礼拜堂。",
        "中午顺看圣彼得大教堂和广场，穹顶可选登顶。",
        "下午串联三座大教堂，傍晚回住处附近收尾。",
      ],
      highlights: [
        "圣彼得大教堂：Free，需安检；穹顶可选 €8。",
        "圣彼得广场：Free。",
        "圣若望拉特兰大殿：Free。",
        "耶路撒冷圣十字教堂：Free。",
        "圣母大殿：Free。",
      ],
      food: ["coda alla vaccinara", "trippa alla romana"],
      tips: [
        "西斯廷礼拜堂禁止拍照。",
        "三座大殿顺路串联即可，不需要专门绕路。",
      ],
      mapCenter: [41.9045, 12.4912],
      mapZoom: 12,
      spots: [
        { order: 1, label: "梵蒂冈博物馆", coords: [41.9065, 12.4536], note: "上午跟团入口。", googleQuery: "Vatican Museums" },
        { order: 2, label: "圣彼得大教堂", coords: [41.9022, 12.4539], note: "《黄金之风》《战斗潮流》背景。", googleQuery: "St. Peter's Basilica" },
        { order: 3, label: "圣彼得广场", coords: [41.9023, 12.457], note: "贝尔尼尼柱廊。", googleQuery: "Saint Peter's Square Vatican" },
        { order: 4, label: "圣若望拉特兰大殿", coords: [41.8862, 12.5056], note: "世界所有教堂之母。", googleQuery: "San Giovanni in Laterano" },
        { order: 5, label: "耶路撒冷圣十字教堂", coords: [41.8909, 12.5096], note: "安静，人少。", googleQuery: "Santa Croce in Gerusalemme Rome" },
        { order: 6, label: "圣母大殿", coords: [41.8975, 12.4986], note: "门口即是 Termini 一带。", googleQuery: "Basilica Papale di Santa Maria Maggiore" },
      ],
    },
    {
      id: "day-4",
      short: "Day 4",
      title: "6月13日 · 移动日 → 佛罗伦萨",
      city: "佛罗伦萨",
      theme: "移动日（10:35 出发）+ 傍晚全景",
      alert: "高铁 10:35 从 Roma Termini 出发，请务必 09:50 前到站。",
      transport: [
        "退房后直奔 Roma Termini。",
        "10:35 高铁出发，12:11 抵达 Firenze Santa Maria Novella。",
        "民宿在 Via Cosimo Rosselli 42 附近，步行约 20 分钟或公交 1/6 路。",
      ],
      plan: [
        "入住后去圣洛伦佐市场附近吃午餐。",
        "下午走圣十字教堂、韦奇奥桥和 Oltrarno。",
        "傍晚上米开朗基罗广场和圣米尼亚托教堂看全景。",
      ],
      highlights: [
        "圣洛伦佐市场：Free 进入。",
        "圣十字教堂：€10。",
        "韦奇奥桥：Free。",
        "Oltrarno：佛罗伦萨生活区。",
        "米开朗基罗广场：Free。",
        "圣米尼亚托教堂：Free。",
      ],
      food: ["Mercato di San Lorenzo", "街边 panini"],
      tips: [
        "佛罗伦萨老城比罗马更适合纯步行。",
        "日落机位热门，想拍照就提前到米开朗基罗广场。",
      ],
      mapCenter: [43.7687, 11.2584],
      mapZoom: 13,
      spots: [
        { order: 1, label: "圣洛伦佐市场", coords: [43.7769, 11.2524], note: "先吃饭。", googleQuery: "Mercato di San Lorenzo Florence" },
        { order: 2, label: "圣十字教堂", coords: [43.7687, 11.2626], note: "JoJo 穿城打卡区。", googleQuery: "Basilica of Santa Croce Florence" },
        { order: 3, label: "韦奇奥桥", coords: [43.768, 11.2531], note: "JoJo 场景附近。", googleQuery: "Ponte Vecchio Florence" },
        { order: 4, label: "Oltrarno", coords: [43.766, 11.2474], note: "南岸生活街区。", googleQuery: "Oltrarno Florence" },
        { order: 5, label: "米开朗基罗广场", coords: [43.7629, 11.2651], note: "全城日落机位。", googleQuery: "Piazzale Michelangelo Florence" },
        { order: 6, label: "圣米尼亚托教堂", coords: [43.7609, 11.2657], note: "人更少，视野更高。", googleQuery: "San Miniato al Monte Florence" },
      ],
    },
    {
      id: "day-5",
      short: "Day 5",
      title: "6月14日 · 佛罗伦萨全天",
      city: "佛罗伦萨",
      theme: "大教堂 + 乌菲兹",
      alert: "Duomo 相关项目最好提前预约，否则当天排队会非常久。",
      transport: [
        "上午在 Duomo 广场集中活动。",
        "下午步行去乌菲兹即可。",
        "傍晚顺到西尼奥里亚广场。",
      ],
      plan: [
        "上午看大教堂、钟楼、洗礼堂。",
        "午间去圣洛伦佐区或 Oltrarno 吃饭，避开主广场高价餐厅。",
        "15:00 乌菲兹，傍晚西尼奥里亚广场，晚餐考虑佛罗伦萨牛排。",
      ],
      highlights: [
        "大教堂外观：Free。",
        "大教堂内部：€0，需联票预约入场。",
        "乔托钟楼：€18（联票含）。",
        "圣乔瓦尼洗礼堂：联票含。",
        "联票约 €30，duomo.firenze.it 预约。",
        "乌菲兹美术馆：€29，建议提前购票。",
        "西尼奥里亚广场：Free。",
      ],
      food: ["ribollita", "pappa al pomodoro", "bistecca alla fiorentina"],
      tips: [
        "穹顶和钟楼二选一即可，不必都爬。",
        "佛罗伦萨牛排按重量计价，下单前先确认份量。",
      ],
      mapCenter: [43.7716, 11.2558],
      mapZoom: 14,
      spots: [
        { order: 1, label: "圣母百花大教堂", coords: [43.7731, 11.256], note: "《黄金之风》标志背景。", googleQuery: "Florence Cathedral" },
        { order: 2, label: "乔托钟楼", coords: [43.7729, 11.2554], note: "平视穹顶的视角。", googleQuery: "Giotto's Campanile Florence" },
        { order: 3, label: "圣乔瓦尼洗礼堂", coords: [43.7733, 11.2548], note: "同片区一起完成。", googleQuery: "Baptistery of St. John Florence" },
        { order: 4, label: "乌菲兹美术馆", coords: [43.7687, 11.2556], note: "下午重点。", googleQuery: "Uffizi Gallery Florence" },
        { order: 5, label: "西尼奥里亚广场", coords: [43.7696, 11.2558], note: "旧宫外观和露天雕塑群。", googleQuery: "Piazza della Signoria Florence" },
      ],
    },
    {
      id: "day-6",
      short: "Day 6",
      title: "6月15日 · 移动日 → 威尼斯（Mestre）",
      city: "威尼斯",
      theme: "移动日（10:20 出发）+ 运河游览",
      alert: "从 Mestre 进岛很方便，但一定留意返程火车时间。",
      transport: [
        "09:30 前从住处出门去 Firenze SMN。",
        "10:20 高铁出发，12:23 抵达 Venezia Mestre。",
        "入住后乘普通火车 10 分钟进岛，€1.5-2.5。",
      ],
      plan: [
        "午餐先在 Mestre 解决，放下行李再进岛。",
        "下午从圣卢西亚站、圣西莫内皮科洛、里亚托桥一路走到圣马可广场。",
        "晚上在 bacaro 吃 cicchetti，留足余量回 Mestre。",
      ],
      highlights: [
        "里亚托桥：Free。",
        "自由桥外景：Free，进岛必经方向。",
        "圣西莫内·皮科洛教堂：外观 Free。",
        "圣马可广场：Free，18:00 后人流略少。",
        "bacaro：spritz + cicchetti 的高性价比组合。",
      ],
      food: ["spritz", "cicchetti"],
      tips: [
        "行李不要带着进城折腾。",
        "回程不要赶最后一班火车，至少留 20 分钟余量。",
      ],
      mapCenter: [45.4381, 12.3343],
      mapZoom: 13,
      spots: [
        { order: 1, label: "圣卢西亚火车站", coords: [45.441, 12.321], note: "进出岛必经。", googleQuery: "Venezia Santa Lucia" },
        { order: 2, label: "圣西莫内·皮科洛教堂", coords: [45.4409, 12.3197], note: "车站对面即见。", googleQuery: "San Simeone Piccolo Venice" },
        { order: 3, label: "里亚托桥", coords: [45.438, 12.3359], note: "JoJo 威尼斯段场景。", googleQuery: "Ponte di Rialto Venice" },
        { order: 4, label: "自由桥外景方向", coords: [45.4398, 12.3131], note: "作为进岛参考外景。", googleQuery: "Ponte della Libertà Venice" },
        { order: 5, label: "圣马可广场", coords: [45.4342, 12.3389], note: "狮子柱是 JoJo 直接出镜点。", googleQuery: "Piazza San Marco Venice" },
      ],
    },
    {
      id: "day-7",
      short: "Day 7",
      title: "6月16日 · 威尼斯上午 → 回程",
      city: "威尼斯",
      theme: "上午游览 + 18:35 回程",
      alert: "13:30 左右从 Mestre 去机场最稳妥，返程优先级最高。",
      transport: [
        "上午轻装进岛，中午前回 Mestre。",
        "13:30 从 Mestre 乘 ATVO 大巴或出租车前往 VCE，约 20 分钟。",
        "14:00 到机场，18:35 航班起飞。",
      ],
      timing: [
        "上午：轻松游览圣马可片区。",
        "13:00：最晚返回 Mestre 民宿取行李退房。",
        "13:30：从 Mestre 前往 VCE 机场。",
        "14:00：抵达机场，办理值机与安检。",
        "18:35：航班起飞。",
      ],
      plan: [
        "上午聚焦圣马可片区。",
        "如时间允许再去圣乔治马焦雷岛；不够就直接删掉这条支线。",
        "10:30 左右从圣马可区域开始回撤。",
      ],
      highlights: [
        "圣马可大教堂：建议提前预约免排队，€3。",
        "圣马可钟楼：€10。",
        "叹息桥：外观 Free。",
        "圣乔治马焦雷岛：Vaporetto 2 号线可达，钟楼 €8。",
      ],
      food: ["简餐咖啡", "机场前轻食"],
      tips: [
        "最后一天只带随身小包进岛。",
        "天气差时直接砍掉离岛支线，保留机场缓冲时间。",
      ],
      mapCenter: [45.4336, 12.3396],
      mapZoom: 15,
      spots: [
        { order: 1, label: "圣马可大教堂", coords: [45.4345, 12.3397], note: "内部金色马赛克是重点。", googleQuery: "Basilica di San Marco Venice" },
        { order: 2, label: "圣马可钟楼", coords: [45.434, 12.3393], note: "俯瞰全城。", googleQuery: "St Mark's Campanile Venice" },
        { order: 3, label: "叹息桥", coords: [45.4341, 12.3408], note: "总督宫旁拍照点。", googleQuery: "Bridge of Sighs Venice" },
        { order: 4, label: "圣乔治马焦雷岛", coords: [45.4297, 12.3432], note: "可选 JoJo 最终对决原型地。", googleQuery: "San Giorgio Maggiore Venice" },
      ],
    },
  ],
  foodGuide: [
    {
      city: "罗马特色",
      items: [
        { name: "Carbonara", note: "培根蛋黄意面，经典做法不加奶油。" },
        { name: "Cacio e pepe", note: "奶酪黑胡椒意面，越简单越见功力。" },
        { name: "Amatriciana", note: "番茄培根意面，味道更厚重。" },
        { name: "Saltimbocca alla romana", note: "火腿鼠尾草小牛肉片。" },
        { name: "Coda alla vaccinara", note: "番茄炖牛尾，老城区特色。" },
        { name: "Trippa alla romana", note: "番茄炖牛肚，周四是传统日。" },
        { name: "Suppli", note: "罗马版炸饭团，适合路边快吃。" },
        { name: "Artichoke alla giudia", note: "犹太风格炸洋蓟，Trastevere 和犹太区值得找。" },
      ],
    },
    {
      city: "佛罗伦萨特色",
      items: [
        { name: "Bistecca alla fiorentina", note: "大 T 骨牛排，半生熟，按公斤计价；下单前确认份量。" },
        { name: "Ribollita", note: "托斯卡纳蔬菜面包汤。" },
        { name: "Pappa al pomodoro", note: "番茄面包糊，朴素但很当地。" },
        { name: "Lampredotto", note: "牛胃三明治，本地街头代表。" },
        { name: "Cantucci con Vin Santo", note: "杏仁脆饼蘸甜白葡萄酒，适合作为饭后收尾。" },
      ],
    },
    {
      city: "威尼斯特色",
      items: [
        { name: "Cicchetti", note: "bacaro 小食拼盘，最适合边走边吃。" },
        { name: "Sarde in saor", note: "甜酸腌沙丁鱼，老派威尼斯味道。" },
        { name: "Baccala mantecato", note: "奶油鳕鱼泥，抹面包吃。" },
        { name: "Spritz", note: "Aperol 或 Campari 加 prosecco，威尼斯标配。" },
        { name: "Risotto al nero di seppia", note: "墨鱼汁黑色炖饭，城市代表菜。" },
      ],
    },
  ],
  foodTips: [
    "早餐文化是站在吧台喝 espresso + cornetto，比坐下便宜很多。",
    "午餐可以在 Carrefour、Conad、Esselunga 买食材，把预算留给晚餐。",
    "避开景点正门前 100 米内的餐厅，往里走 2 条街通常更稳。",
    "点水时说“acqua del rubinetto”，避免默认上瓶装水。",
  ],
  safetyGuide: [
    {
      title: "扒手高发区",
      items: [
        "罗马：地铁 A 线、Termini、Barberini、斗兽场周边、特雷维喷泉夜间。",
        "佛罗伦萨：大教堂广场、韦奇奥桥拥挤时段。",
        "威尼斯岛：圣马可广场和 Vaporetto 上下船时。",
      ],
    },
    {
      title: "Solo旅行注意事项",
      items: [
        "贵重物品放胸前斜挎包或腰包，护照尽量留在民宿。",
        "手机尽量别在人流密集处边走边掏出来看地图。",
        "Termini 周边夜晚尽量打车，不走偏僻小路。",
        "Mestre 夜间以普通住宅区为主，仍然以主路和照明好路段为先。",
      ],
    },
    {
      title: "紧急信息",
      items: [
        "意大利报警电话：112。",
        "建议出发前配置含医疗、行李和航班取消的旅行保险。",
        "GHIC 卡可在 nhs.uk/apply-for-ghic 免费申请。",
      ],
    },
  ],
  bookings: [
    { status: "已购", item: "FR1542 机票 EMA → CIA", date: "6月10日", note: "确认值机时间。" },
    { status: "已购", item: "罗马 → 佛罗伦萨高铁 10:35", date: "6月13日", note: "09:50 前到 Termini。" },
    { status: "已购", item: "佛罗伦萨 → 威尼斯 Mestre 高铁 10:20", date: "6月15日", note: "10:00 前到 SMN。" },
    { status: "已购", item: "FR2899 机票 VCE → MAN", date: "6月16日", note: "建议提前网上值机。" },
    { status: "已购", item: "斗兽场跟团票", date: "6月11日 13:45", note: "确认集合地点。" },
    { status: "已购", item: "梵蒂冈跟团票", date: "6月12日 09:00", note: "确认集合地点。" },
    { status: "待购", item: "乌菲兹美术馆 €29", date: "6月14日", note: "uffizi.it，尽早购。" },
    { status: "待购", item: "ATVO 机场大巴（Mestre → VCE）€10", date: "6月16日", note: "atvo.it，或直接打车。" },
    { status: "可选", item: "佛罗伦萨大教堂联票 €30", date: "6月14日", note: "duomo.firenze.it。" },
    { status: "可选", item: "圣马可大教堂免排队票 €3", date: "6月16日", note: "venetoinside.com。" },
  ],
  budget: [
    { title: "景点门票", amount: "约 €100-120", note: "含乌菲兹、大教堂联票、卡拉卡拉浴场、圣乔治马焦雷钟楼等；斗兽场和梵蒂冈已含。" },
    { title: "城市间及机场交通", amount: "约 €25", note: "主要是机场大巴两次。" },
    { title: "日常饮食", amount: "约 €175-245", note: "按 €25-35 / 天估算，共 7 天。" },
    { title: "市内交通", amount: "约 €35", note: "含地铁、Vaporetto、Mestre 往返进岛火车。" },
    { title: "总计参考", amount: "约 €335-425", note: "不含已购机票、火车与住宿。" },
  ],
  jojo: {
    included: [
      { city: "罗马", spot: "斗兽场（Colosseo）", scene: "《战斗潮流》地下层柱之男研究场所；《黄金之风》尾声", note: "Day 2 跟团已含", coords: [41.8902, 12.4922], googleQuery: "Colosseum Rome" },
      { city: "罗马", spot: "君士坦丁凯旋门", scene: "《黄金之风》背景", note: "Day 2 顺路", coords: [41.8898, 12.4909], googleQuery: "Arch of Constantine Rome" },
      { city: "罗马", spot: "圣天使堡及圣天使桥", scene: "Bucciarati vs. Secco 战斗场景；桥上天使雕塑", note: "Day 1 傍晚顺路", coords: [41.9031, 12.4663], googleQuery: "Castel Sant'Angelo Rome" },
      { city: "罗马", spot: "圣彼得大教堂", scene: "《黄金之风》《战斗潮流》背景出现", note: "Day 3 含", coords: [41.9022, 12.4539], googleQuery: "St. Peter's Basilica" },
      { city: "罗马", spot: "纳沃纳广场", scene: "《黄金之风》城市背景", note: "Day 1 顺路", coords: [41.8992, 12.4731], googleQuery: "Piazza Navona Rome" },
      { city: "佛罗伦萨", spot: "圣母百花大教堂穹顶", scene: "《黄金之风》OP 及城市背景标志", note: "Day 5 含", coords: [43.7731, 11.256], googleQuery: "Florence Cathedral" },
      { city: "佛罗伦萨", spot: "韦奇奥桥", scene: "阿巴奇奥与纳兰西亚场景附近", note: "Day 4 含", coords: [43.768, 11.2531], googleQuery: "Ponte Vecchio Florence" },
      { city: "威尼斯", spot: "里亚托桥", scene: "《黄金之风》威尼斯段场景", note: "Day 6 含", coords: [45.438, 12.3359], googleQuery: "Ponte di Rialto Venice" },
      { city: "威尼斯", spot: "圣马可广场狮子柱", scene: "《黄金之风》直接出镜", note: "Day 6 含", coords: [45.4342, 12.3389], googleQuery: "Lion of Venice Saint Mark's Square" },
      { city: "威尼斯", spot: "自由桥外景", scene: "Mista vs. Ghiaccio 追车场景", note: "Day 6 进岛可见", coords: [45.4398, 12.3131], googleQuery: "Ponte della Libertà Venice" },
      { city: "威尼斯", spot: "圣西莫内·皮科洛教堂", scene: "《黄金之风》场景", note: "Day 6 顺路", coords: [45.4409, 12.3197], googleQuery: "San Simeone Piccolo Venice" },
      { city: "威尼斯", spot: "圣乔治马焦雷岛", scene: "Boss 最终对决原型地", note: "Day 7 可选", coords: [45.4297, 12.3432], googleQuery: "San Giorgio Maggiore Venice" },
      { city: "威尼斯", spot: "圣卢西亚火车站", scene: "OA-DISC 场景，Mista vs. Ghiaccio 起点", note: "进出岛必经", coords: [45.441, 12.321], googleQuery: "Venezia Santa Lucia" },
    ],
    extra: [
      { city: "罗马", spot: "托雷·德莱·米利齐", scene: "Giorno vs. Cioccolata 战斗建筑原型", note: "本次未安排，可作为补充参考。", coords: [41.8957, 12.4874], googleQuery: "Torre delle Milizie Rome" },
      { city: "罗马", spot: "Vittoriano 纪念堂", scene: "《黄金之风》城市背景", note: "本次未安排，可和市中心步行串联。", coords: [41.8955, 12.4823], googleQuery: "Altare della Patria Rome" },
    ],
  },
};
